#!/usr/bin/env python3
"""Generate agl_calls.h: an inline call for every function in agl_lib.fd.

usage: aglcalls.py <agl_lib.fd> <agl_calls.h>

The inline/macros.h LP macros cannot pass arguments in fp registers (they list
fp0/fp1 as clobbered), and StormMESA passes floats and doubles in fp0-fp7. So
each call is written out with its own register variables:
- dN: integer (ULONG), aN: pointer (const void *), fpN: float, or double when
  the argument name says GLdouble/GLclampd.
- Every call returns d0 as ULONG; the caller casts it where needed.
"""
import re
import sys

ENTRY = re.compile(r"^(\w+)\(([^)]*)\)\(([^)]*)\)")
SCRATCH = ["d0", "d1", "a0", "a1", "fp0", "fp1"]


def c_type(arg, reg):
    if reg.startswith("fp"):
        return "double" if re.match(r"(const_)?GL(double|clampd)", arg) else "float"
    if reg.startswith("a"):
        return "const void *"
    return "ULONG"


def call(name, args, regs, lvo):
    params = ", ".join("%s %s" % (c_type(a, r), "p%d" % i) for i, (a, r) in enumerate(zip(args, regs))) or "void"
    lines = ["static inline ULONG %s(%s) {" % (name, params)]
    outputs, result = [], None
    for i, (arg, reg) in enumerate(zip(args, regs)):
        ctype = c_type(arg, reg)
        if reg.startswith("a"):
            ctype = "ULONG"  # held as an address in the register
            value = "(ULONG) p%d" % i
        else:
            value = "p%d" % i
        lines.append('\tregister %s r%d __asm("%s") = %s;' % (ctype, i, reg, value))
        outputs.append('"+%s" (r%d)' % ("f" if reg.startswith("fp") else "r", i))
        if reg == "d0":
            result = "r%d" % i
    if result is None:
        lines.append('\tregister ULONG d0 __asm("d0");')
        outputs.insert(0, '"=r" (d0)')
        result = "d0"
    lines.append('\tregister struct Library *base __asm("a6") = aglBase;')
    clobbers = ['"%s"' % r for r in SCRATCH if r not in regs and r != "d0"]
    clobbers += ['"cc"', '"memory"']
    lines.append('\t__asm volatile ("jsr a6@(-%d:W)"' % lvo)
    lines.append("\t\t: %s" % ", ".join(outputs))
    lines.append('\t\t: "r" (base)')
    lines.append("\t\t: %s);" % ", ".join(clobbers))
    lines.append("\treturn %s;" % result)
    lines.append("}")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    out = ["/* Generated by tests/aglcalls.py from %s - do not edit */" % sys.argv[1],
           "#ifndef QUARKTEX_AGL_CALLS_H", "#define QUARKTEX_AGL_CALLS_H",
           "#include <exec/types.h>", "extern struct Library *aglBase;", ""]
    offset = None
    with open(sys.argv[1], encoding="latin-1") as fd:
        for line in fd:
            line = line.strip()
            if line.startswith("##bias"):
                bias = int(line.split()[1])
                offset = bias if offset is None or bias > offset else offset
                continue
            if not line or line.startswith("*") or line.startswith("##"):
                continue
            match = ENTRY.match(line)
            if not match:
                sys.exit("cannot parse: " + line)
            name, args, regs = match.groups()
            args = [a for a in args.split(",") if a]
            regs = [r.lower() for r in re.split(r"[/,]", regs) if r]
            if len(args) != len(regs):
                sys.exit("argument and register counts differ: " + line)
            if offset is None:
                offset = 30
            if not name.startswith("Dummy_"):
                out.append(call(name, args, regs, offset))
                out.append("")
            offset += 6
    out.append("#endif")
    with open(sys.argv[2], "w") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
