<#
.SYNOPSIS
Runs an Amiga program (a game or demo) with the current QuarkTex build in the
private, portable WinUAE of tests/run.ps1, and captures some of its frames.

.DESCRIPTION
Boots the AmigaOS installation of tests/settings.local.psd1 read-only as the
reference tests do, with the current Warp3D.library and agl.library (and
-ExtraLibs, for example a minigl.library) in front of LIBS:. -VolumeDir is
mounted read-write as the volume -Volume, so give it a copy of the program,
not the original: programs write their configuration and logs. Then
-Command runs from -Directory on that volume, with its output in
build/apps/<label>/capture/app.log.

The program is not expected to quit; WinUAE is stopped after -TimeoutSec.
Every -CaptureEvery-th buffer swap of each context is saved as a BMP in
build/apps/<label>/capture, as are QuarkTexLog.txt and the program's output.

.EXAMPLE
pwsh tests/run-app.ps1 -VolumeDir C:\Temp\Share -Volume Share -Directory JK2_Pistorm -Command jk2sp `
	-ExtraLibs C:\MiniGL\bin\minigl.library -Label jk2sp
#>
param(
	[Parameter(Mandatory)] [string]$VolumeDir,
	[string]$Volume = 'Share',
	[string]$Directory = '',
	[Parameter(Mandatory)] [string]$Command,
	[string[]]$ExtraLibs = @(),
	[string]$Label = 'app',
	[ValidateSet('winuae.exe', 'winuae64.exe')]
	[string]$Emulator = 'winuae64.exe',
	[int]$TimeoutSec = 240,
	[int]$CaptureEvery = 25,
	[int]$Z3MemMB = 512,
	[int]$StackBytes = 2200000,
	# Log the Warp3D texture commands (QUARKTEX_TRACE), and all Warp3D commands,
	# with the first vertices of each array, of the given buffer swap
	# (QUARKTEX_TRACE_FRAME), into QuarkTexLog.txt.
	[switch]$Trace,
	[int]$TraceFrame = -1,
	[string]$Settings = (Join-Path $PSScriptRoot 'settings.local.psd1')
)

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$cfg = Import-PowerShellDataFile $Settings
$uaequit = Join-Path $cfg.WinUAEDir 'Amiga Programs\UAEquit'
foreach ($path in $cfg.Kickstart, $cfg.HardFile, $VolumeDir, (Join-Path $cfg.WinUAEDir $Emulator),
		(Join-Path $root 'build\amiga\Warp3D.library'), (Join-Path $root 'build\host-x64\quarktex-windows-x86-64.dll')) {
	if (-not (Test-Path $path)) { throw "Not found: $path" }
}

function Write-AmigaText([string]$path, [string[]]$lines) {
	[IO.File]::WriteAllText($path, (($lines -join "`n") + "`n"), [Text.Encoding]::ASCII)
}

# The portable WinUAE of tests/run.ps1, with the current host DLLs.
$uae = Join-Path $root 'build\tests\winuae'
New-Item -ItemType Directory -Force $uae | Out-Null
Copy-Item (Join-Path $cfg.WinUAEDir $Emulator) $uae -Force
if (-not (Test-Path (Join-Path $uae 'winuae.ini'))) { New-Item -ItemType File (Join-Path $uae 'winuae.ini') | Out-Null }
Copy-Item (Join-Path $root 'build\host-x86\quarktex-windows-x86.dll'), (Join-Path $root 'build\host-x64\quarktex-windows-x86-64.dll') $uae -Force

$dir = Join-Path $root "build\apps\$Label"
$qttest = Join-Path $dir 'qttest'
if (Test-Path $qttest) { Remove-Item $qttest -Recurse -Force }
foreach ($sub in 'Libs', 'C', 'S', 'capture') { New-Item -ItemType Directory -Force (Join-Path $qttest $sub) | Out-Null }
Copy-Item (Join-Path $root 'build\amiga\Warp3D.library'), (Join-Path $root 'build\amiga\agl.library') (Join-Path $qttest 'Libs')
foreach ($lib in $ExtraLibs) { Copy-Item $lib (Join-Path $qttest 'Libs') }
Copy-Item $uaequit (Join-Path $qttest 'C')
Write-AmigaText (Join-Path $qttest 'capture\label.txt') @($Label)

$where = if ($Directory) { "${Volume}:$Directory" } else { "${Volume}:" }
# AmigaDOS takes the redirection only right after the command name.
$name, $arguments = $Command -split ' ', 2
$redirected = "$name >QTTEST:capture/app.log $arguments".TrimEnd()
Write-AmigaText (Join-Path $qttest 'S\run-tests') @(
	'; Generated by tests/run-app.ps1', 'FailAt 21', "Stack $StackBytes",
	"CD $where", 'Avail >QTTEST:capture/avail.txt', $redirected, 'Avail >>QTTEST:capture/avail.txt', 'QTTEST:C/UAEquit')

$template = (Get-Content (Join-Path $PSScriptRoot 'winuae\test.uae.in') -Raw).
	Replace('@KICKSTART@', $cfg.Kickstart).Replace('@HARDFILE@', $cfg.HardFile).
	Replace('@BOOTDIR@', (Join-Path $PSScriptRoot 'amiga\boot')).Replace('@TESTDIR@', $qttest).
	Replace('@JITCACHE@', '16384').
	Replace('z3mem_size=256', "z3mem_size=$Z3MemMB").
	Replace('cpu_type=68040', 'cpu_type=68060').Replace('cpu_model=68040', 'cpu_model=68060').
	Replace('fpu_model=68040', 'fpu_model=68060')
$template += "filesystem2=rw,${Volume}:${Volume}:$VolumeDir,-128`n"
$config = Join-Path $dir 'app.uae'
Set-Content -Path $config -Value $template -Encoding ASCII

Write-Host "== $Label`: $Command in $where, $Emulator, $TimeoutSec s, every $CaptureEvery. frame"
$env:QUARKTEX_CAPTURE_DIR = Join-Path $qttest 'capture'
$env:QUARKTEX_CAPTURE_EVERY = "$CaptureEvery"
if ($Trace) { $env:QUARKTEX_TRACE = '1' }
if ($TraceFrame -ge 0) { $env:QUARKTEX_TRACE_FRAME = "$TraceFrame" }
# The host writes its log only when it has something to say: an old one
# must not be taken for this run's.
Remove-Item (Join-Path $uae 'QuarkTexLog.txt') -ErrorAction SilentlyContinue
$process = Start-Process (Join-Path $uae $Emulator) -ArgumentList '-f', "`"$config`"" -WorkingDirectory $uae -PassThru
if (-not $process.WaitForExit($TimeoutSec * 1000)) {
	Stop-Process $process -Force
	Write-Host "   stopped after $TimeoutSec s"
}
Remove-Item Env:QUARKTEX_CAPTURE_DIR, Env:QUARKTEX_CAPTURE_EVERY
Remove-Item Env:QUARKTEX_TRACE, Env:QUARKTEX_TRACE_FRAME -ErrorAction SilentlyContinue
$hostLog = Join-Path $uae 'QuarkTexLog.txt'
if (Test-Path $hostLog) { Copy-Item $hostLog (Join-Path $qttest 'capture') -Force }
Get-ChildItem (Join-Path $qttest 'capture') | Select-Object Name, Length | Format-Table -AutoSize | Out-String | Write-Host
