<#
.SYNOPSIS
Runs the Warp3D reference tests in WinUAE and compares the rendered frames of
the original QuarkTex 0.53 libraries ("orig") with the current build ("new").

.DESCRIPTION
Needs ./build.sh and ./build.sh tests to have run first. The tests run in a
private, portable copy of WinUAE under build/tests/winuae, so the normal WinUAE
installation is not touched. That copy gets the current host libraries
(quarktex-windows-*.dll) and, for the 0.53 libraries, the legacy
QuarkTex.alib; both capture frames. The AmigaOS hard file is mounted
read-only. Close WinUAE before running.

Settings (paths to WinUAE, Kickstart and the hard file) are read from
tests/settings.local.psd1; see tests/settings.example.psd1.

.EXAMPLE
pwsh tests/run.ps1
pwsh tests/run.ps1 -Variants new -TimeoutSec 120
pwsh tests/run.ps1 -Emulator winuae64.exe   # the 0.53 run always uses winuae.exe
#>
param(
	[string]$Settings = (Join-Path $PSScriptRoot 'settings.local.psd1'),
	[ValidateSet('orig', 'new')]
	[string[]]$Variants = @('orig', 'new'),
	# Emulator for the current build. The 0.53 libraries need the uaelib traps
	# of the 32-bit winuae.exe and always run there.
	[ValidateSet('winuae.exe', 'winuae64.exe')]
	[string]$Emulator = 'winuae.exe',
	[int]$TimeoutSec = 300,
	# Run the 68k code with the JIT compiler (16 MB cache), as games usually do.
	[switch]$Jit
)

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$work = Join-Path $root 'build\tests'

if (-not (Test-Path $Settings)) {
	throw "Settings file not found: $Settings (copy tests/settings.example.psd1 to tests/settings.local.psd1)"
}
$cfg = Import-PowerShellDataFile $Settings
foreach ($key in 'WinUAEDir', 'Kickstart', 'HardFile') {
	if (-not $cfg[$key]) { throw "$key is missing in $Settings" }
}
$uaequit = Join-Path $cfg.WinUAEDir 'Amiga Programs\UAEquit'
foreach ($path in (Join-Path $cfg.WinUAEDir 'winuae.exe'), (Join-Path $cfg.WinUAEDir $Emulator), $cfg.Kickstart, $cfg.HardFile, $uaequit,
		(Join-Path $root 'build\host-x86\quarktex-windows-x86.dll'), (Join-Path $root 'build\host-x64\quarktex-windows-x86-64.dll'),
		(Join-Path $root 'build\legacy\QuarkTex.alib'), (Join-Path $root 'build\amiga\Warp3D.library'),
		(Join-Path $root 'build\tests\amiga')) {
	if (-not (Test-Path $path)) { throw "Not found: $path (run ./build.sh and ./build.sh tests first?)" }
}
if (Get-Process winuae -ErrorAction SilentlyContinue) {
	Write-Warning 'WinUAE is already running; it may hold the hard file open.'
}

function Write-AmigaText([string]$path, [string[]]$lines) {
	# AmigaDOS wants LF line endings and no BOM.
	[IO.File]::WriteAllText($path, (($lines -join "`n") + "`n"), [Text.Encoding]::ASCII)
}

# Private portable WinUAE (winuae.ini next to the exe keeps it out of the registry).
$uae = Join-Path $work 'winuae'
New-Item -ItemType Directory -Force (Join-Path $uae 'alib') | Out-Null
Copy-Item (Join-Path $cfg.WinUAEDir 'winuae.exe'), (Join-Path $cfg.WinUAEDir $Emulator) $uae -Force
if (-not (Test-Path (Join-Path $uae 'winuae.ini'))) { New-Item -ItemType File (Join-Path $uae 'winuae.ini') | Out-Null }
Copy-Item (Join-Path $root 'build\host-x86\quarktex-windows-x86.dll'), (Join-Path $root 'build\host-x64\quarktex-windows-x86-64.dll') $uae -Force
Copy-Item (Join-Path $root 'build\legacy\QuarkTex.alib') (Join-Path $uae 'alib') -Force

# Original QuarkTex 0.53 libraries from Aminet.
$orig = Join-Path $work 'orig-0.53'
if ($Variants -contains 'orig' -and -not (Test-Path (Join-Path $orig 'Warp3D.library'))) {
	New-Item -ItemType Directory -Force $orig | Out-Null
	$zip = Join-Path $orig 'QuarkTex.zip'
	Invoke-WebRequest 'https://aminet.net/driver/video/QuarkTex.zip' -OutFile $zip
	Expand-Archive $zip -DestinationPath $orig -Force
}

$tests = Get-ChildItem (Join-Path $root 'build\tests\amiga') -File |
	Where-Object { $_.Name -match '^[ta]\d\d_[a-z0-9_]+$' } | Sort-Object Name
$template = Get-Content (Join-Path $PSScriptRoot 'winuae\test.uae.in') -Raw

foreach ($variant in $Variants) {
	$dir = Join-Path $work $variant
	$qttest = Join-Path $dir 'qttest'
	if (Test-Path $qttest) { Remove-Item $qttest -Recurse -Force }
	foreach ($sub in 'Libs', 'Tests', 'C', 'S', 'capture') { New-Item -ItemType Directory -Force (Join-Path $qttest $sub) | Out-Null }

	$libs = if ($variant -eq 'orig') { $orig } else { Join-Path $root 'build\amiga' }
	Copy-Item (Join-Path $libs 'Warp3D.library'), (Join-Path $libs 'agl.library') (Join-Path $qttest 'Libs')
	$tests | Copy-Item -Destination (Join-Path $qttest 'Tests')
	Copy-Item $uaequit (Join-Path $qttest 'C')

	$script = @('; Generated by tests/run.ps1', 'FailAt 21', 'Stack 65536',
		"Echo `"QuarkTex tests ($variant)`" >QTTEST:capture/amiga.log")
	foreach ($test in $tests) { $script += "QTTEST:Tests/$($test.Name) >>QTTEST:capture/amiga.log" }
	$script += 'Echo "done" >>QTTEST:capture/amiga.log', 'QTTEST:C/UAEquit'
	Write-AmigaText (Join-Path $qttest 'S\run-tests') $script

	$config = Join-Path $dir 'test.uae'
	$template.Replace('@KICKSTART@', $cfg.Kickstart).Replace('@HARDFILE@', $cfg.HardFile).
		Replace('@BOOTDIR@', (Join-Path $PSScriptRoot 'amiga\boot')).Replace('@TESTDIR@', $qttest).
		Replace('@JITCACHE@', $(if ($Jit) { '16384' } else { '0' })) |
		Set-Content -Path $config -Encoding ASCII

	$exe = if ($variant -eq 'orig') { 'winuae.exe' } else { $Emulator }
	# A WinUAE from the previous run may still be shutting down; runs started
	# right after one another sometimes produced no output at all.
	for ($wait = 0; $wait -lt 20; ++$wait) {
		$running = Get-Process winuae, winuae64 -ErrorAction SilentlyContinue |
			Where-Object { $_.Path -and $_.Path.StartsWith($uae, [StringComparison]::OrdinalIgnoreCase) }
		if (-not $running) { break }
		Start-Sleep -Milliseconds 500
	}
	Write-Host "== ${variant}: running $($tests.Count) tests in $exe (timeout $TimeoutSec s)"
	$env:QUARKTEX_CAPTURE_DIR = Join-Path $qttest 'capture'
	$watch = [Diagnostics.Stopwatch]::StartNew()
	$process = Start-Process (Join-Path $uae $exe) -ArgumentList '-f', "`"$config`"" -WorkingDirectory $uae -PassThru
	if (-not $process.WaitForExit($TimeoutSec * 1000)) {
		Stop-Process $process -Force
		Write-Warning "${variant}: WinUAE did not quit within $TimeoutSec s; the results are incomplete."
	}
	Write-Host ("   WinUAE ran for {0:N1} s (wall clock, boot included)" -f $watch.Elapsed.TotalSeconds)
	Remove-Item Env:QUARKTEX_CAPTURE_DIR
	$log = Join-Path $qttest 'capture\amiga.log'
	if (Test-Path $log) { Get-Content $log | ForEach-Object { Write-Host "   $_" } }
	else { Write-Warning "${variant}: no amiga.log - the test script did not run." }
}

# Compare with the last 0.53 run, also when only the new build ran now.
if ($Variants -contains 'new' -and (Test-Path (Join-Path $work 'orig\qttest\capture'))) {
	Write-Host '== comparing'
	docker run --rm -v "${root}:/w" -w /w quarktex-host python3 tests/compare.py `
		build/tests/orig/qttest/capture build/tests/new/qttest/capture build/tests/report
	$result = $LASTEXITCODE
	Write-Host "Report: $(Join-Path $work 'report\index.html')"
	exit $result
}
