/* Generated by gl/glgen.cpp from gl/glFuncs.txt - do not edit */
GLvoid _glAccum(GLenum op, GLfloat value) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (1UL << 16) | 3;
	qt_w[1] = (ULONG) op;
	qt_w[2] = qt_f2l(value);
}
GLvoid _glAlphaFunc(GLenum func, GLclampf ref) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (2UL << 16) | 3;
	qt_w[1] = (ULONG) func;
	qt_w[2] = qt_f2l(ref);
}
GLboolean _glAreTexturesResident(GLsizei n, GLuint* textures, GLboolean* residences) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (3UL << 16) | 4;
	qt_w[1] = (ULONG) n;
	qt_w[2] = QT_ADDRESS(textures);
	qt_w[3] = QT_ADDRESS(residences);
	return (GLboolean) qt_flush();
}
GLvoid _glArrayElement(GLint i) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (4UL << 16) | 2;
	qt_w[1] = (ULONG) i;
}
GLvoid _glBegin(GLenum mode) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (5UL << 16) | 2;
	qt_w[1] = (ULONG) mode;
}
GLvoid _glBindTexture(GLenum target, GLuint texture) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (6UL << 16) | 3;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) texture;
}
GLvoid _glBitmap(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, GLubyte* bitmap) {
	ULONG *qt_w = qt_reserve(8);
	qt_w[0] = (7UL << 16) | 8;
	qt_w[1] = (ULONG) width;
	qt_w[2] = (ULONG) height;
	qt_w[3] = qt_f2l(xorig);
	qt_w[4] = qt_f2l(yorig);
	qt_w[5] = qt_f2l(xmove);
	qt_w[6] = qt_f2l(ymove);
	qt_w[7] = QT_ADDRESS(bitmap);
	qt_flush();
}
GLvoid _glBlendFunc(GLenum sfactor, GLenum dfactor) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (8UL << 16) | 3;
	qt_w[1] = (ULONG) sfactor;
	qt_w[2] = (ULONG) dfactor;
}
GLvoid _glCallList(GLuint list) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (9UL << 16) | 2;
	qt_w[1] = (ULONG) list;
}
GLvoid _glCallLists(GLsizei n, GLenum type, GLvoid* lists) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (10UL << 16) | 4;
	qt_w[1] = (ULONG) n;
	qt_w[2] = (ULONG) type;
	qt_w[3] = QT_ADDRESS(lists);
	qt_flush();
}
GLvoid _glClear(GLbitfield mask) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (11UL << 16) | 2;
	qt_w[1] = (ULONG) mask;
}
GLvoid _glClearAccum(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (12UL << 16) | 5;
	qt_w[1] = qt_f2l(red);
	qt_w[2] = qt_f2l(green);
	qt_w[3] = qt_f2l(blue);
	qt_w[4] = qt_f2l(alpha);
}
GLvoid _glClearColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (13UL << 16) | 5;
	qt_w[1] = qt_f2l(red);
	qt_w[2] = qt_f2l(green);
	qt_w[3] = qt_f2l(blue);
	qt_w[4] = qt_f2l(alpha);
}
GLvoid _glClearDepth(GLclampd depth) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (14UL << 16) | 3;
	qt_w[1] = qt_dhi(depth);
	qt_w[2] = qt_dlo(depth);
}
GLvoid _glClearIndex(GLfloat c) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (15UL << 16) | 2;
	qt_w[1] = qt_f2l(c);
}
GLvoid _glClearStencil(GLint s) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (16UL << 16) | 2;
	qt_w[1] = (ULONG) s;
}
GLvoid _glClipPlane(GLenum plane, GLdouble* equation) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (17UL << 16) | 3;
	qt_w[1] = (ULONG) plane;
	qt_w[2] = QT_ADDRESS(equation);
	qt_flush();
}
GLvoid _glColor3b(GLbyte red, GLbyte green, GLbyte blue) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (18UL << 16) | 4;
	qt_w[1] = (ULONG) red;
	qt_w[2] = (ULONG) green;
	qt_w[3] = (ULONG) blue;
}
GLvoid _glColor3bv(GLbyte* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (19UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glColor3d(GLdouble red, GLdouble green, GLdouble blue) {
	ULONG *qt_w = qt_reserve(7);
	qt_w[0] = (20UL << 16) | 7;
	qt_w[1] = qt_dhi(red);
	qt_w[2] = qt_dlo(red);
	qt_w[3] = qt_dhi(green);
	qt_w[4] = qt_dlo(green);
	qt_w[5] = qt_dhi(blue);
	qt_w[6] = qt_dlo(blue);
}
GLvoid _glColor3dv(GLdouble* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (21UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glColor3f(GLfloat red, GLfloat green, GLfloat blue) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (22UL << 16) | 4;
	qt_w[1] = qt_f2l(red);
	qt_w[2] = qt_f2l(green);
	qt_w[3] = qt_f2l(blue);
}
GLvoid _glColor3fv(GLfloat* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (23UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glColor3i(GLint red, GLint green, GLint blue) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (24UL << 16) | 4;
	qt_w[1] = (ULONG) red;
	qt_w[2] = (ULONG) green;
	qt_w[3] = (ULONG) blue;
}
GLvoid _glColor3iv(GLint* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (25UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glColor3s(GLshort red, GLshort green, GLshort blue) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (26UL << 16) | 4;
	qt_w[1] = (ULONG) red;
	qt_w[2] = (ULONG) green;
	qt_w[3] = (ULONG) blue;
}
GLvoid _glColor3sv(GLshort* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (27UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glColor3ub(GLubyte red, GLubyte green, GLubyte blue) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (28UL << 16) | 4;
	qt_w[1] = (ULONG) red;
	qt_w[2] = (ULONG) green;
	qt_w[3] = (ULONG) blue;
}
GLvoid _glColor3ubv(GLubyte* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (29UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glColor3ui(GLuint red, GLuint green, GLuint blue) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (30UL << 16) | 4;
	qt_w[1] = (ULONG) red;
	qt_w[2] = (ULONG) green;
	qt_w[3] = (ULONG) blue;
}
GLvoid _glColor3uiv(GLuint* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (31UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glColor3us(GLushort red, GLushort green, GLushort blue) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (32UL << 16) | 4;
	qt_w[1] = (ULONG) red;
	qt_w[2] = (ULONG) green;
	qt_w[3] = (ULONG) blue;
}
GLvoid _glColor3usv(GLushort* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (33UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glColor4b(GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (34UL << 16) | 5;
	qt_w[1] = (ULONG) red;
	qt_w[2] = (ULONG) green;
	qt_w[3] = (ULONG) blue;
	qt_w[4] = (ULONG) alpha;
}
GLvoid _glColor4bv(GLbyte* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (35UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glColor4d(GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha) {
	ULONG *qt_w = qt_reserve(9);
	qt_w[0] = (36UL << 16) | 9;
	qt_w[1] = qt_dhi(red);
	qt_w[2] = qt_dlo(red);
	qt_w[3] = qt_dhi(green);
	qt_w[4] = qt_dlo(green);
	qt_w[5] = qt_dhi(blue);
	qt_w[6] = qt_dlo(blue);
	qt_w[7] = qt_dhi(alpha);
	qt_w[8] = qt_dlo(alpha);
}
GLvoid _glColor4dv(GLdouble* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (37UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glColor4f(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (38UL << 16) | 5;
	qt_w[1] = qt_f2l(red);
	qt_w[2] = qt_f2l(green);
	qt_w[3] = qt_f2l(blue);
	qt_w[4] = qt_f2l(alpha);
}
GLvoid _glColor4fv(GLfloat* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (39UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glColor4i(GLint red, GLint green, GLint blue, GLint alpha) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (40UL << 16) | 5;
	qt_w[1] = (ULONG) red;
	qt_w[2] = (ULONG) green;
	qt_w[3] = (ULONG) blue;
	qt_w[4] = (ULONG) alpha;
}
GLvoid _glColor4iv(GLint* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (41UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glColor4s(GLshort red, GLshort green, GLshort blue, GLshort alpha) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (42UL << 16) | 5;
	qt_w[1] = (ULONG) red;
	qt_w[2] = (ULONG) green;
	qt_w[3] = (ULONG) blue;
	qt_w[4] = (ULONG) alpha;
}
GLvoid _glColor4sv(GLshort* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (43UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glColor4ub(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (44UL << 16) | 5;
	qt_w[1] = (ULONG) red;
	qt_w[2] = (ULONG) green;
	qt_w[3] = (ULONG) blue;
	qt_w[4] = (ULONG) alpha;
}
GLvoid _glColor4ubv(GLubyte* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (45UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glColor4ui(GLuint red, GLuint green, GLuint blue, GLuint alpha) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (46UL << 16) | 5;
	qt_w[1] = (ULONG) red;
	qt_w[2] = (ULONG) green;
	qt_w[3] = (ULONG) blue;
	qt_w[4] = (ULONG) alpha;
}
GLvoid _glColor4uiv(GLuint* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (47UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glColor4us(GLushort red, GLushort green, GLushort blue, GLushort alpha) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (48UL << 16) | 5;
	qt_w[1] = (ULONG) red;
	qt_w[2] = (ULONG) green;
	qt_w[3] = (ULONG) blue;
	qt_w[4] = (ULONG) alpha;
}
GLvoid _glColor4usv(GLushort* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (49UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (50UL << 16) | 5;
	qt_w[1] = (ULONG) red;
	qt_w[2] = (ULONG) green;
	qt_w[3] = (ULONG) blue;
	qt_w[4] = (ULONG) alpha;
}
GLvoid _glColorMaterial(GLenum face, GLenum mode) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (51UL << 16) | 3;
	qt_w[1] = (ULONG) face;
	qt_w[2] = (ULONG) mode;
}
GLvoid _glColorPointer(GLint size, GLenum type, GLsizei stride, GLvoid* pointer) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (52UL << 16) | 5;
	qt_w[1] = (ULONG) size;
	qt_w[2] = (ULONG) type;
	qt_w[3] = (ULONG) stride;
	qt_w[4] = QT_ADDRESS(pointer);
	qt_flush();
}
GLvoid _glCopyPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type) {
	ULONG *qt_w = qt_reserve(6);
	qt_w[0] = (53UL << 16) | 6;
	qt_w[1] = (ULONG) x;
	qt_w[2] = (ULONG) y;
	qt_w[3] = (ULONG) width;
	qt_w[4] = (ULONG) height;
	qt_w[5] = (ULONG) type;
}
GLvoid _glCopyTexImage1D(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border) {
	ULONG *qt_w = qt_reserve(8);
	qt_w[0] = (54UL << 16) | 8;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) level;
	qt_w[3] = (ULONG) internalFormat;
	qt_w[4] = (ULONG) x;
	qt_w[5] = (ULONG) y;
	qt_w[6] = (ULONG) width;
	qt_w[7] = (ULONG) border;
}
GLvoid _glCopyTexImage2D(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border) {
	ULONG *qt_w = qt_reserve(9);
	qt_w[0] = (55UL << 16) | 9;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) level;
	qt_w[3] = (ULONG) internalFormat;
	qt_w[4] = (ULONG) x;
	qt_w[5] = (ULONG) y;
	qt_w[6] = (ULONG) width;
	qt_w[7] = (ULONG) height;
	qt_w[8] = (ULONG) border;
}
GLvoid _glCopyTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width) {
	ULONG *qt_w = qt_reserve(7);
	qt_w[0] = (56UL << 16) | 7;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) level;
	qt_w[3] = (ULONG) xoffset;
	qt_w[4] = (ULONG) x;
	qt_w[5] = (ULONG) y;
	qt_w[6] = (ULONG) width;
}
GLvoid _glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height) {
	ULONG *qt_w = qt_reserve(9);
	qt_w[0] = (57UL << 16) | 9;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) level;
	qt_w[3] = (ULONG) xoffset;
	qt_w[4] = (ULONG) yoffset;
	qt_w[5] = (ULONG) x;
	qt_w[6] = (ULONG) y;
	qt_w[7] = (ULONG) width;
	qt_w[8] = (ULONG) height;
}
GLvoid _glCullFace(GLenum mode) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (58UL << 16) | 2;
	qt_w[1] = (ULONG) mode;
}
GLvoid _glDeleteLists(GLuint list, GLsizei range) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (59UL << 16) | 3;
	qt_w[1] = (ULONG) list;
	qt_w[2] = (ULONG) range;
}
GLvoid _glDeleteTextures(GLsizei n, GLuint* textures) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (60UL << 16) | 3;
	qt_w[1] = (ULONG) n;
	qt_w[2] = QT_ADDRESS(textures);
	qt_flush();
}
GLvoid _glDepthFunc(GLenum func) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (61UL << 16) | 2;
	qt_w[1] = (ULONG) func;
}
GLvoid _glDepthMask(GLboolean flag) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (62UL << 16) | 2;
	qt_w[1] = (ULONG) flag;
}
GLvoid _glDepthRange(GLclampd zNear, GLclampd zFar) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (63UL << 16) | 5;
	qt_w[1] = qt_dhi(zNear);
	qt_w[2] = qt_dlo(zNear);
	qt_w[3] = qt_dhi(zFar);
	qt_w[4] = qt_dlo(zFar);
}
GLvoid _glDisable(GLenum cap) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (64UL << 16) | 2;
	qt_w[1] = (ULONG) cap;
}
GLvoid _glDisableClientState(GLenum array) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (65UL << 16) | 2;
	qt_w[1] = (ULONG) array;
}
GLvoid _glDrawArrays(GLenum mode, GLint first, GLsizei count) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (66UL << 16) | 4;
	qt_w[1] = (ULONG) mode;
	qt_w[2] = (ULONG) first;
	qt_w[3] = (ULONG) count;
}
GLvoid _glDrawBuffer(GLenum mode) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (67UL << 16) | 2;
	qt_w[1] = (ULONG) mode;
}
GLvoid _glDrawElements(GLenum mode, GLsizei count, GLenum type, GLvoid* indices) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (68UL << 16) | 5;
	qt_w[1] = (ULONG) mode;
	qt_w[2] = (ULONG) count;
	qt_w[3] = (ULONG) type;
	qt_w[4] = QT_ADDRESS(indices);
	qt_flush();
}
GLvoid _glDrawPixels(GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* pixels) {
	ULONG *qt_w = qt_reserve(6);
	qt_w[0] = (69UL << 16) | 6;
	qt_w[1] = (ULONG) width;
	qt_w[2] = (ULONG) height;
	qt_w[3] = (ULONG) format;
	qt_w[4] = (ULONG) type;
	qt_w[5] = QT_ADDRESS(pixels);
	qt_flush();
}
GLvoid _glEdgeFlag(GLboolean flag) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (70UL << 16) | 2;
	qt_w[1] = (ULONG) flag;
}
GLvoid _glEdgeFlagPointer(GLsizei stride, GLvoid* pointer) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (71UL << 16) | 3;
	qt_w[1] = (ULONG) stride;
	qt_w[2] = QT_ADDRESS(pointer);
	qt_flush();
}
GLvoid _glEdgeFlagv(GLboolean* flag) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (72UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(flag);
	qt_flush();
}
GLvoid _glEnable(GLenum cap) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (73UL << 16) | 2;
	qt_w[1] = (ULONG) cap;
}
GLvoid _glEnableClientState(GLenum array) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (74UL << 16) | 2;
	qt_w[1] = (ULONG) array;
}
GLvoid _glEnd(void) {
	ULONG *qt_w = qt_reserve(1);
	qt_w[0] = (75UL << 16) | 1;
}
GLvoid _glEndList(void) {
	ULONG *qt_w = qt_reserve(1);
	qt_w[0] = (76UL << 16) | 1;
}
GLvoid _glEvalCoord1d(GLdouble u) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (77UL << 16) | 3;
	qt_w[1] = qt_dhi(u);
	qt_w[2] = qt_dlo(u);
}
GLvoid _glEvalCoord1dv(GLdouble* u) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (78UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(u);
	qt_flush();
}
GLvoid _glEvalCoord1f(GLfloat u) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (79UL << 16) | 2;
	qt_w[1] = qt_f2l(u);
}
GLvoid _glEvalCoord1fv(GLfloat* u) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (80UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(u);
	qt_flush();
}
GLvoid _glEvalCoord2d(GLdouble u, GLdouble v) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (81UL << 16) | 5;
	qt_w[1] = qt_dhi(u);
	qt_w[2] = qt_dlo(u);
	qt_w[3] = qt_dhi(v);
	qt_w[4] = qt_dlo(v);
}
GLvoid _glEvalCoord2dv(GLdouble* u) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (82UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(u);
	qt_flush();
}
GLvoid _glEvalCoord2f(GLfloat u, GLfloat v) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (83UL << 16) | 3;
	qt_w[1] = qt_f2l(u);
	qt_w[2] = qt_f2l(v);
}
GLvoid _glEvalCoord2fv(GLfloat* u) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (84UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(u);
	qt_flush();
}
GLvoid _glEvalMesh1(GLenum mode, GLint i1, GLint i2) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (85UL << 16) | 4;
	qt_w[1] = (ULONG) mode;
	qt_w[2] = (ULONG) i1;
	qt_w[3] = (ULONG) i2;
}
GLvoid _glEvalMesh2(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2) {
	ULONG *qt_w = qt_reserve(6);
	qt_w[0] = (86UL << 16) | 6;
	qt_w[1] = (ULONG) mode;
	qt_w[2] = (ULONG) i1;
	qt_w[3] = (ULONG) i2;
	qt_w[4] = (ULONG) j1;
	qt_w[5] = (ULONG) j2;
}
GLvoid _glEvalPoint1(GLint i) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (87UL << 16) | 2;
	qt_w[1] = (ULONG) i;
}
GLvoid _glEvalPoint2(GLint i, GLint j) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (88UL << 16) | 3;
	qt_w[1] = (ULONG) i;
	qt_w[2] = (ULONG) j;
}
GLvoid _glFeedbackBuffer(GLsizei size, GLenum type, GLfloat* buffer) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (89UL << 16) | 4;
	qt_w[1] = (ULONG) size;
	qt_w[2] = (ULONG) type;
	qt_w[3] = QT_ADDRESS(buffer);
	qt_flush();
}
GLvoid _glFinish(void) {
	ULONG *qt_w = qt_reserve(1);
	qt_w[0] = (90UL << 16) | 1;
	qt_flush();
}
GLvoid _glFlush(void) {
	ULONG *qt_w = qt_reserve(1);
	qt_w[0] = (91UL << 16) | 1;
	qt_flush();
}
GLvoid _glFogf(GLenum pname, GLfloat param) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (92UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = qt_f2l(param);
}
GLvoid _glFogfv(GLenum pname, GLfloat* params) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (93UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glFogi(GLenum pname, GLint param) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (94UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = (ULONG) param;
}
GLvoid _glFogiv(GLenum pname, GLint* params) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (95UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glFrontFace(GLenum mode) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (96UL << 16) | 2;
	qt_w[1] = (ULONG) mode;
}
GLvoid _glFrustum(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar) {
	ULONG *qt_w = qt_reserve(13);
	qt_w[0] = (97UL << 16) | 13;
	qt_w[1] = qt_dhi(left);
	qt_w[2] = qt_dlo(left);
	qt_w[3] = qt_dhi(right);
	qt_w[4] = qt_dlo(right);
	qt_w[5] = qt_dhi(bottom);
	qt_w[6] = qt_dlo(bottom);
	qt_w[7] = qt_dhi(top);
	qt_w[8] = qt_dlo(top);
	qt_w[9] = qt_dhi(zNear);
	qt_w[10] = qt_dlo(zNear);
	qt_w[11] = qt_dhi(zFar);
	qt_w[12] = qt_dlo(zFar);
}
GLuint _glGenLists(GLsizei range) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (98UL << 16) | 2;
	qt_w[1] = (ULONG) range;
	return (GLuint) qt_flush();
}
GLvoid _glGenTextures(GLsizei n, GLuint* textures) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (99UL << 16) | 3;
	qt_w[1] = (ULONG) n;
	qt_w[2] = QT_ADDRESS(textures);
	qt_flush();
}
GLvoid _glGetBooleanv(GLenum pname, GLboolean* params) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (100UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glGetClipPlane(GLenum plane, GLdouble* equation) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (101UL << 16) | 3;
	qt_w[1] = (ULONG) plane;
	qt_w[2] = QT_ADDRESS(equation);
	qt_flush();
}
GLvoid _glGetDoublev(GLenum pname, GLdouble* params) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (102UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = QT_ADDRESS(params);
	qt_flush();
}
GLenum _glGetError(void) {
	ULONG *qt_w = qt_reserve(1);
	qt_w[0] = (103UL << 16) | 1;
	return (GLenum) qt_flush();
}
GLvoid _glGetFloatv(GLenum pname, GLfloat* params) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (104UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glGetIntegerv(GLenum pname, GLint* params) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (105UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glGetLightfv(GLenum light, GLenum pname, GLfloat* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (106UL << 16) | 4;
	qt_w[1] = (ULONG) light;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glGetLightiv(GLenum light, GLenum pname, GLint* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (107UL << 16) | 4;
	qt_w[1] = (ULONG) light;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glGetMapdv(GLenum target, GLenum query, GLdouble* v) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (108UL << 16) | 4;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) query;
	qt_w[3] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glGetMapfv(GLenum target, GLenum query, GLfloat* v) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (109UL << 16) | 4;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) query;
	qt_w[3] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glGetMapiv(GLenum target, GLenum query, GLint* v) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (110UL << 16) | 4;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) query;
	qt_w[3] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glGetMaterialfv(GLenum face, GLenum pname, GLfloat* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (111UL << 16) | 4;
	qt_w[1] = (ULONG) face;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glGetMaterialiv(GLenum face, GLenum pname, GLint* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (112UL << 16) | 4;
	qt_w[1] = (ULONG) face;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glGetPixelMapfv(GLenum map, GLfloat* values) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (113UL << 16) | 3;
	qt_w[1] = (ULONG) map;
	qt_w[2] = QT_ADDRESS(values);
	qt_flush();
}
GLvoid _glGetPixelMapuiv(GLenum map, GLuint* values) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (114UL << 16) | 3;
	qt_w[1] = (ULONG) map;
	qt_w[2] = QT_ADDRESS(values);
	qt_flush();
}
GLvoid _glGetPixelMapusv(GLenum map, GLushort* values) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (115UL << 16) | 3;
	qt_w[1] = (ULONG) map;
	qt_w[2] = QT_ADDRESS(values);
	qt_flush();
}
GLvoid _glGetPointerv(GLenum pname, GLvoid** params) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (116UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glGetPolygonStipple(GLubyte* mask) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (117UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(mask);
	qt_flush();
}
GLubyte* _glGetString(GLenum name) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (118UL << 16) | 2;
	qt_w[1] = (ULONG) name;
	return (GLubyte*) qt_flush();
}
GLvoid _glGetTexEnvfv(GLenum target, GLenum pname, GLfloat* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (119UL << 16) | 4;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glGetTexEnviv(GLenum target, GLenum pname, GLint* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (120UL << 16) | 4;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glGetTexGendv(GLenum coord, GLenum pname, GLdouble* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (121UL << 16) | 4;
	qt_w[1] = (ULONG) coord;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glGetTexGenfv(GLenum coord, GLenum pname, GLfloat* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (122UL << 16) | 4;
	qt_w[1] = (ULONG) coord;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glGetTexGeniv(GLenum coord, GLenum pname, GLint* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (123UL << 16) | 4;
	qt_w[1] = (ULONG) coord;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glGetTexImage(GLenum target, GLint level, GLenum format, GLenum type, GLvoid* pixels) {
	ULONG *qt_w = qt_reserve(6);
	qt_w[0] = (124UL << 16) | 6;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) level;
	qt_w[3] = (ULONG) format;
	qt_w[4] = (ULONG) type;
	qt_w[5] = QT_ADDRESS(pixels);
	qt_flush();
}
GLvoid _glGetTexLevelParameterfv(GLenum target, GLint level, GLenum pname, GLfloat* params) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (125UL << 16) | 5;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) level;
	qt_w[3] = (ULONG) pname;
	qt_w[4] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glGetTexLevelParameteriv(GLenum target, GLint level, GLenum pname, GLint* params) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (126UL << 16) | 5;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) level;
	qt_w[3] = (ULONG) pname;
	qt_w[4] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glGetTexParameterfv(GLenum target, GLenum pname, GLfloat* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (127UL << 16) | 4;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glGetTexParameteriv(GLenum target, GLenum pname, GLint* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (128UL << 16) | 4;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glHint(GLenum target, GLenum mode) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (129UL << 16) | 3;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) mode;
}
GLvoid _glIndexMask(GLuint mask) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (130UL << 16) | 2;
	qt_w[1] = (ULONG) mask;
}
GLvoid _glIndexPointer(GLenum type, GLsizei stride, GLvoid* pointer) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (131UL << 16) | 4;
	qt_w[1] = (ULONG) type;
	qt_w[2] = (ULONG) stride;
	qt_w[3] = QT_ADDRESS(pointer);
	qt_flush();
}
GLvoid _glIndexd(GLdouble c) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (132UL << 16) | 3;
	qt_w[1] = qt_dhi(c);
	qt_w[2] = qt_dlo(c);
}
GLvoid _glIndexdv(GLdouble* c) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (133UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(c);
	qt_flush();
}
GLvoid _glIndexf(GLfloat c) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (134UL << 16) | 2;
	qt_w[1] = qt_f2l(c);
}
GLvoid _glIndexfv(GLfloat* c) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (135UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(c);
	qt_flush();
}
GLvoid _glIndexi(GLint c) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (136UL << 16) | 2;
	qt_w[1] = (ULONG) c;
}
GLvoid _glIndexiv(GLint* c) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (137UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(c);
	qt_flush();
}
GLvoid _glIndexs(GLshort c) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (138UL << 16) | 2;
	qt_w[1] = (ULONG) c;
}
GLvoid _glIndexsv(GLshort* c) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (139UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(c);
	qt_flush();
}
GLvoid _glIndexub(GLubyte c) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (140UL << 16) | 2;
	qt_w[1] = (ULONG) c;
}
GLvoid _glIndexubv(GLubyte* c) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (141UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(c);
	qt_flush();
}
GLvoid _glInitNames(void) {
	ULONG *qt_w = qt_reserve(1);
	qt_w[0] = (142UL << 16) | 1;
}
GLvoid _glInterleavedArrays(GLenum format, GLsizei stride, GLvoid* pointer) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (143UL << 16) | 4;
	qt_w[1] = (ULONG) format;
	qt_w[2] = (ULONG) stride;
	qt_w[3] = QT_ADDRESS(pointer);
	qt_flush();
}
GLboolean _glIsEnabled(GLenum cap) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (144UL << 16) | 2;
	qt_w[1] = (ULONG) cap;
	return (GLboolean) qt_flush();
}
GLboolean _glIsList(GLuint list) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (145UL << 16) | 2;
	qt_w[1] = (ULONG) list;
	return (GLboolean) qt_flush();
}
GLboolean _glIsTexture(GLuint texture) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (146UL << 16) | 2;
	qt_w[1] = (ULONG) texture;
	return (GLboolean) qt_flush();
}
GLvoid _glLightModelf(GLenum pname, GLfloat param) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (147UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = qt_f2l(param);
}
GLvoid _glLightModelfv(GLenum pname, GLfloat* params) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (148UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glLightModeli(GLenum pname, GLint param) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (149UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = (ULONG) param;
}
GLvoid _glLightModeliv(GLenum pname, GLint* params) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (150UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glLightf(GLenum light, GLenum pname, GLfloat param) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (151UL << 16) | 4;
	qt_w[1] = (ULONG) light;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = qt_f2l(param);
}
GLvoid _glLightfv(GLenum light, GLenum pname, GLfloat* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (152UL << 16) | 4;
	qt_w[1] = (ULONG) light;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glLighti(GLenum light, GLenum pname, GLint param) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (153UL << 16) | 4;
	qt_w[1] = (ULONG) light;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = (ULONG) param;
}
GLvoid _glLightiv(GLenum light, GLenum pname, GLint* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (154UL << 16) | 4;
	qt_w[1] = (ULONG) light;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glLineStipple(GLint factor, GLushort pattern) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (155UL << 16) | 3;
	qt_w[1] = (ULONG) factor;
	qt_w[2] = (ULONG) pattern;
}
GLvoid _glLineWidth(GLfloat width) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (156UL << 16) | 2;
	qt_w[1] = qt_f2l(width);
}
GLvoid _glListBase(GLuint base) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (157UL << 16) | 2;
	qt_w[1] = (ULONG) base;
}
GLvoid _glLoadIdentity(void) {
	ULONG *qt_w = qt_reserve(1);
	qt_w[0] = (158UL << 16) | 1;
}
GLvoid _glLoadMatrixd(GLdouble* m) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (159UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(m);
	qt_flush();
}
GLvoid _glLoadMatrixf(GLfloat* m) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (160UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(m);
	qt_flush();
}
GLvoid _glLoadName(GLuint name) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (161UL << 16) | 2;
	qt_w[1] = (ULONG) name;
}
GLvoid _glLogicOp(GLenum opcode) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (162UL << 16) | 2;
	qt_w[1] = (ULONG) opcode;
}
GLvoid _glMap1d(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, GLdouble* points) {
	ULONG *qt_w = qt_reserve(9);
	qt_w[0] = (163UL << 16) | 9;
	qt_w[1] = (ULONG) target;
	qt_w[2] = qt_dhi(u1);
	qt_w[3] = qt_dlo(u1);
	qt_w[4] = qt_dhi(u2);
	qt_w[5] = qt_dlo(u2);
	qt_w[6] = (ULONG) stride;
	qt_w[7] = (ULONG) order;
	qt_w[8] = QT_ADDRESS(points);
	qt_flush();
}
GLvoid _glMap1f(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, GLfloat* points) {
	ULONG *qt_w = qt_reserve(7);
	qt_w[0] = (164UL << 16) | 7;
	qt_w[1] = (ULONG) target;
	qt_w[2] = qt_f2l(u1);
	qt_w[3] = qt_f2l(u2);
	qt_w[4] = (ULONG) stride;
	qt_w[5] = (ULONG) order;
	qt_w[6] = QT_ADDRESS(points);
	qt_flush();
}
GLvoid _glMap2d(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, GLdouble* points) {
	ULONG *qt_w = qt_reserve(15);
	qt_w[0] = (165UL << 16) | 15;
	qt_w[1] = (ULONG) target;
	qt_w[2] = qt_dhi(u1);
	qt_w[3] = qt_dlo(u1);
	qt_w[4] = qt_dhi(u2);
	qt_w[5] = qt_dlo(u2);
	qt_w[6] = (ULONG) ustride;
	qt_w[7] = (ULONG) uorder;
	qt_w[8] = qt_dhi(v1);
	qt_w[9] = qt_dlo(v1);
	qt_w[10] = qt_dhi(v2);
	qt_w[11] = qt_dlo(v2);
	qt_w[12] = (ULONG) vstride;
	qt_w[13] = (ULONG) vorder;
	qt_w[14] = QT_ADDRESS(points);
	qt_flush();
}
GLvoid _glMap2f(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, GLfloat* points) {
	ULONG *qt_w = qt_reserve(11);
	qt_w[0] = (166UL << 16) | 11;
	qt_w[1] = (ULONG) target;
	qt_w[2] = qt_f2l(u1);
	qt_w[3] = qt_f2l(u2);
	qt_w[4] = (ULONG) ustride;
	qt_w[5] = (ULONG) uorder;
	qt_w[6] = qt_f2l(v1);
	qt_w[7] = qt_f2l(v2);
	qt_w[8] = (ULONG) vstride;
	qt_w[9] = (ULONG) vorder;
	qt_w[10] = QT_ADDRESS(points);
	qt_flush();
}
GLvoid _glMapGrid1d(GLint un, GLdouble u1, GLdouble u2) {
	ULONG *qt_w = qt_reserve(6);
	qt_w[0] = (167UL << 16) | 6;
	qt_w[1] = (ULONG) un;
	qt_w[2] = qt_dhi(u1);
	qt_w[3] = qt_dlo(u1);
	qt_w[4] = qt_dhi(u2);
	qt_w[5] = qt_dlo(u2);
}
GLvoid _glMapGrid1f(GLint un, GLfloat u1, GLfloat u2) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (168UL << 16) | 4;
	qt_w[1] = (ULONG) un;
	qt_w[2] = qt_f2l(u1);
	qt_w[3] = qt_f2l(u2);
}
GLvoid _glMapGrid2d(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2) {
	ULONG *qt_w = qt_reserve(11);
	qt_w[0] = (169UL << 16) | 11;
	qt_w[1] = (ULONG) un;
	qt_w[2] = qt_dhi(u1);
	qt_w[3] = qt_dlo(u1);
	qt_w[4] = qt_dhi(u2);
	qt_w[5] = qt_dlo(u2);
	qt_w[6] = (ULONG) vn;
	qt_w[7] = qt_dhi(v1);
	qt_w[8] = qt_dlo(v1);
	qt_w[9] = qt_dhi(v2);
	qt_w[10] = qt_dlo(v2);
}
GLvoid _glMapGrid2f(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2) {
	ULONG *qt_w = qt_reserve(7);
	qt_w[0] = (170UL << 16) | 7;
	qt_w[1] = (ULONG) un;
	qt_w[2] = qt_f2l(u1);
	qt_w[3] = qt_f2l(u2);
	qt_w[4] = (ULONG) vn;
	qt_w[5] = qt_f2l(v1);
	qt_w[6] = qt_f2l(v2);
}
GLvoid _glMaterialf(GLenum face, GLenum pname, GLfloat param) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (171UL << 16) | 4;
	qt_w[1] = (ULONG) face;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = qt_f2l(param);
}
GLvoid _glMaterialfv(GLenum face, GLenum pname, GLfloat* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (172UL << 16) | 4;
	qt_w[1] = (ULONG) face;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glMateriali(GLenum face, GLenum pname, GLint param) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (173UL << 16) | 4;
	qt_w[1] = (ULONG) face;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = (ULONG) param;
}
GLvoid _glMaterialiv(GLenum face, GLenum pname, GLint* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (174UL << 16) | 4;
	qt_w[1] = (ULONG) face;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glMatrixMode(GLenum mode) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (175UL << 16) | 2;
	qt_w[1] = (ULONG) mode;
}
GLvoid _glMultMatrixd(GLdouble* m) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (176UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(m);
	qt_flush();
}
GLvoid _glMultMatrixf(GLfloat* m) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (177UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(m);
	qt_flush();
}
GLvoid _glNewList(GLuint list, GLenum mode) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (178UL << 16) | 3;
	qt_w[1] = (ULONG) list;
	qt_w[2] = (ULONG) mode;
}
GLvoid _glNormal3b(GLbyte nx, GLbyte ny, GLbyte nz) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (179UL << 16) | 4;
	qt_w[1] = (ULONG) nx;
	qt_w[2] = (ULONG) ny;
	qt_w[3] = (ULONG) nz;
}
GLvoid _glNormal3bv(GLbyte* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (180UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glNormal3d(GLdouble nx, GLdouble ny, GLdouble nz) {
	ULONG *qt_w = qt_reserve(7);
	qt_w[0] = (181UL << 16) | 7;
	qt_w[1] = qt_dhi(nx);
	qt_w[2] = qt_dlo(nx);
	qt_w[3] = qt_dhi(ny);
	qt_w[4] = qt_dlo(ny);
	qt_w[5] = qt_dhi(nz);
	qt_w[6] = qt_dlo(nz);
}
GLvoid _glNormal3dv(GLdouble* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (182UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glNormal3f(GLfloat nx, GLfloat ny, GLfloat nz) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (183UL << 16) | 4;
	qt_w[1] = qt_f2l(nx);
	qt_w[2] = qt_f2l(ny);
	qt_w[3] = qt_f2l(nz);
}
GLvoid _glNormal3fv(GLfloat* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (184UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glNormal3i(GLint nx, GLint ny, GLint nz) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (185UL << 16) | 4;
	qt_w[1] = (ULONG) nx;
	qt_w[2] = (ULONG) ny;
	qt_w[3] = (ULONG) nz;
}
GLvoid _glNormal3iv(GLint* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (186UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glNormal3s(GLshort nx, GLshort ny, GLshort nz) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (187UL << 16) | 4;
	qt_w[1] = (ULONG) nx;
	qt_w[2] = (ULONG) ny;
	qt_w[3] = (ULONG) nz;
}
GLvoid _glNormal3sv(GLshort* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (188UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glNormalPointer(GLenum type, GLsizei stride, GLvoid* pointer) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (189UL << 16) | 4;
	qt_w[1] = (ULONG) type;
	qt_w[2] = (ULONG) stride;
	qt_w[3] = QT_ADDRESS(pointer);
	qt_flush();
}
GLvoid _glOrtho(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar) {
	ULONG *qt_w = qt_reserve(13);
	qt_w[0] = (190UL << 16) | 13;
	qt_w[1] = qt_dhi(left);
	qt_w[2] = qt_dlo(left);
	qt_w[3] = qt_dhi(right);
	qt_w[4] = qt_dlo(right);
	qt_w[5] = qt_dhi(bottom);
	qt_w[6] = qt_dlo(bottom);
	qt_w[7] = qt_dhi(top);
	qt_w[8] = qt_dlo(top);
	qt_w[9] = qt_dhi(zNear);
	qt_w[10] = qt_dlo(zNear);
	qt_w[11] = qt_dhi(zFar);
	qt_w[12] = qt_dlo(zFar);
}
GLvoid _glPassThrough(GLfloat token) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (191UL << 16) | 2;
	qt_w[1] = qt_f2l(token);
}
GLvoid _glPixelMapfv(GLenum map, GLsizei mapsize, GLfloat* values) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (192UL << 16) | 4;
	qt_w[1] = (ULONG) map;
	qt_w[2] = (ULONG) mapsize;
	qt_w[3] = QT_ADDRESS(values);
	qt_flush();
}
GLvoid _glPixelMapuiv(GLenum map, GLsizei mapsize, GLuint* values) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (193UL << 16) | 4;
	qt_w[1] = (ULONG) map;
	qt_w[2] = (ULONG) mapsize;
	qt_w[3] = QT_ADDRESS(values);
	qt_flush();
}
GLvoid _glPixelMapusv(GLenum map, GLsizei mapsize, GLushort* values) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (194UL << 16) | 4;
	qt_w[1] = (ULONG) map;
	qt_w[2] = (ULONG) mapsize;
	qt_w[3] = QT_ADDRESS(values);
	qt_flush();
}
GLvoid _glPixelStoref(GLenum pname, GLfloat param) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (195UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = qt_f2l(param);
}
GLvoid _glPixelStorei(GLenum pname, GLint param) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (196UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = (ULONG) param;
}
GLvoid _glPixelTransferf(GLenum pname, GLfloat param) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (197UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = qt_f2l(param);
}
GLvoid _glPixelTransferi(GLenum pname, GLint param) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (198UL << 16) | 3;
	qt_w[1] = (ULONG) pname;
	qt_w[2] = (ULONG) param;
}
GLvoid _glPixelZoom(GLfloat xfactor, GLfloat yfactor) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (199UL << 16) | 3;
	qt_w[1] = qt_f2l(xfactor);
	qt_w[2] = qt_f2l(yfactor);
}
GLvoid _glPointSize(GLfloat size) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (200UL << 16) | 2;
	qt_w[1] = qt_f2l(size);
}
GLvoid _glPolygonMode(GLenum face, GLenum mode) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (201UL << 16) | 3;
	qt_w[1] = (ULONG) face;
	qt_w[2] = (ULONG) mode;
}
GLvoid _glPolygonOffset(GLfloat factor, GLfloat units) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (202UL << 16) | 3;
	qt_w[1] = qt_f2l(factor);
	qt_w[2] = qt_f2l(units);
}
GLvoid _glPolygonStipple(GLubyte* mask) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (203UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(mask);
	qt_flush();
}
GLvoid _glPopAttrib(void) {
	ULONG *qt_w = qt_reserve(1);
	qt_w[0] = (204UL << 16) | 1;
}
GLvoid _glPopClientAttrib(void) {
	ULONG *qt_w = qt_reserve(1);
	qt_w[0] = (205UL << 16) | 1;
}
GLvoid _glPopMatrix(void) {
	ULONG *qt_w = qt_reserve(1);
	qt_w[0] = (206UL << 16) | 1;
}
GLvoid _glPopName(void) {
	ULONG *qt_w = qt_reserve(1);
	qt_w[0] = (207UL << 16) | 1;
}
GLvoid _glPrioritizeTextures(GLsizei n, GLuint* textures, GLclampf* priorities) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (208UL << 16) | 4;
	qt_w[1] = (ULONG) n;
	qt_w[2] = QT_ADDRESS(textures);
	qt_w[3] = QT_ADDRESS(priorities);
	qt_flush();
}
GLvoid _glPushAttrib(GLbitfield mask) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (209UL << 16) | 2;
	qt_w[1] = (ULONG) mask;
}
GLvoid _glPushClientAttrib(GLbitfield mask) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (210UL << 16) | 2;
	qt_w[1] = (ULONG) mask;
}
GLvoid _glPushMatrix(void) {
	ULONG *qt_w = qt_reserve(1);
	qt_w[0] = (211UL << 16) | 1;
}
GLvoid _glPushName(GLuint name) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (212UL << 16) | 2;
	qt_w[1] = (ULONG) name;
}
GLvoid _glRasterPos2d(GLdouble x, GLdouble y) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (213UL << 16) | 5;
	qt_w[1] = qt_dhi(x);
	qt_w[2] = qt_dlo(x);
	qt_w[3] = qt_dhi(y);
	qt_w[4] = qt_dlo(y);
}
GLvoid _glRasterPos2dv(GLdouble* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (214UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glRasterPos2f(GLfloat x, GLfloat y) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (215UL << 16) | 3;
	qt_w[1] = qt_f2l(x);
	qt_w[2] = qt_f2l(y);
}
GLvoid _glRasterPos2fv(GLfloat* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (216UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glRasterPos2i(GLint x, GLint y) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (217UL << 16) | 3;
	qt_w[1] = (ULONG) x;
	qt_w[2] = (ULONG) y;
}
GLvoid _glRasterPos2iv(GLint* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (218UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glRasterPos2s(GLshort x, GLshort y) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (219UL << 16) | 3;
	qt_w[1] = (ULONG) x;
	qt_w[2] = (ULONG) y;
}
GLvoid _glRasterPos2sv(GLshort* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (220UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glRasterPos3d(GLdouble x, GLdouble y, GLdouble z) {
	ULONG *qt_w = qt_reserve(7);
	qt_w[0] = (221UL << 16) | 7;
	qt_w[1] = qt_dhi(x);
	qt_w[2] = qt_dlo(x);
	qt_w[3] = qt_dhi(y);
	qt_w[4] = qt_dlo(y);
	qt_w[5] = qt_dhi(z);
	qt_w[6] = qt_dlo(z);
}
GLvoid _glRasterPos3dv(GLdouble* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (222UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glRasterPos3f(GLfloat x, GLfloat y, GLfloat z) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (223UL << 16) | 4;
	qt_w[1] = qt_f2l(x);
	qt_w[2] = qt_f2l(y);
	qt_w[3] = qt_f2l(z);
}
GLvoid _glRasterPos3fv(GLfloat* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (224UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glRasterPos3i(GLint x, GLint y, GLint z) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (225UL << 16) | 4;
	qt_w[1] = (ULONG) x;
	qt_w[2] = (ULONG) y;
	qt_w[3] = (ULONG) z;
}
GLvoid _glRasterPos3iv(GLint* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (226UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glRasterPos3s(GLshort x, GLshort y, GLshort z) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (227UL << 16) | 4;
	qt_w[1] = (ULONG) x;
	qt_w[2] = (ULONG) y;
	qt_w[3] = (ULONG) z;
}
GLvoid _glRasterPos3sv(GLshort* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (228UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glRasterPos4d(GLdouble x, GLdouble y, GLdouble z, GLdouble w) {
	ULONG *qt_w = qt_reserve(9);
	qt_w[0] = (229UL << 16) | 9;
	qt_w[1] = qt_dhi(x);
	qt_w[2] = qt_dlo(x);
	qt_w[3] = qt_dhi(y);
	qt_w[4] = qt_dlo(y);
	qt_w[5] = qt_dhi(z);
	qt_w[6] = qt_dlo(z);
	qt_w[7] = qt_dhi(w);
	qt_w[8] = qt_dlo(w);
}
GLvoid _glRasterPos4dv(GLdouble* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (230UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glRasterPos4f(GLfloat x, GLfloat y, GLfloat z, GLfloat w) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (231UL << 16) | 5;
	qt_w[1] = qt_f2l(x);
	qt_w[2] = qt_f2l(y);
	qt_w[3] = qt_f2l(z);
	qt_w[4] = qt_f2l(w);
}
GLvoid _glRasterPos4fv(GLfloat* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (232UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glRasterPos4i(GLint x, GLint y, GLint z, GLint w) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (233UL << 16) | 5;
	qt_w[1] = (ULONG) x;
	qt_w[2] = (ULONG) y;
	qt_w[3] = (ULONG) z;
	qt_w[4] = (ULONG) w;
}
GLvoid _glRasterPos4iv(GLint* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (234UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glRasterPos4s(GLshort x, GLshort y, GLshort z, GLshort w) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (235UL << 16) | 5;
	qt_w[1] = (ULONG) x;
	qt_w[2] = (ULONG) y;
	qt_w[3] = (ULONG) z;
	qt_w[4] = (ULONG) w;
}
GLvoid _glRasterPos4sv(GLshort* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (236UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glReadBuffer(GLenum mode) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (237UL << 16) | 2;
	qt_w[1] = (ULONG) mode;
}
GLvoid _glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* pixels) {
	ULONG *qt_w = qt_reserve(8);
	qt_w[0] = (238UL << 16) | 8;
	qt_w[1] = (ULONG) x;
	qt_w[2] = (ULONG) y;
	qt_w[3] = (ULONG) width;
	qt_w[4] = (ULONG) height;
	qt_w[5] = (ULONG) format;
	qt_w[6] = (ULONG) type;
	qt_w[7] = QT_ADDRESS(pixels);
	qt_flush();
}
GLvoid _glRectd(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2) {
	ULONG *qt_w = qt_reserve(9);
	qt_w[0] = (239UL << 16) | 9;
	qt_w[1] = qt_dhi(x1);
	qt_w[2] = qt_dlo(x1);
	qt_w[3] = qt_dhi(y1);
	qt_w[4] = qt_dlo(y1);
	qt_w[5] = qt_dhi(x2);
	qt_w[6] = qt_dlo(x2);
	qt_w[7] = qt_dhi(y2);
	qt_w[8] = qt_dlo(y2);
}
GLvoid _glRectdv(GLdouble* v1, GLdouble* v2) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (240UL << 16) | 3;
	qt_w[1] = QT_ADDRESS(v1);
	qt_w[2] = QT_ADDRESS(v2);
	qt_flush();
}
GLvoid _glRectf(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (241UL << 16) | 5;
	qt_w[1] = qt_f2l(x1);
	qt_w[2] = qt_f2l(y1);
	qt_w[3] = qt_f2l(x2);
	qt_w[4] = qt_f2l(y2);
}
GLvoid _glRectfv(GLfloat* v1, GLfloat* v2) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (242UL << 16) | 3;
	qt_w[1] = QT_ADDRESS(v1);
	qt_w[2] = QT_ADDRESS(v2);
	qt_flush();
}
GLvoid _glRecti(GLint x1, GLint y1, GLint x2, GLint y2) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (243UL << 16) | 5;
	qt_w[1] = (ULONG) x1;
	qt_w[2] = (ULONG) y1;
	qt_w[3] = (ULONG) x2;
	qt_w[4] = (ULONG) y2;
}
GLvoid _glRectiv(GLint* v1, GLint* v2) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (244UL << 16) | 3;
	qt_w[1] = QT_ADDRESS(v1);
	qt_w[2] = QT_ADDRESS(v2);
	qt_flush();
}
GLvoid _glRects(GLshort x1, GLshort y1, GLshort x2, GLshort y2) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (245UL << 16) | 5;
	qt_w[1] = (ULONG) x1;
	qt_w[2] = (ULONG) y1;
	qt_w[3] = (ULONG) x2;
	qt_w[4] = (ULONG) y2;
}
GLvoid _glRectsv(GLshort* v1, GLshort* v2) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (246UL << 16) | 3;
	qt_w[1] = QT_ADDRESS(v1);
	qt_w[2] = QT_ADDRESS(v2);
	qt_flush();
}
GLint _glRenderMode(GLenum mode) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (247UL << 16) | 2;
	qt_w[1] = (ULONG) mode;
	return (GLint) qt_flush();
}
GLvoid _glRotated(GLdouble ane, GLdouble x, GLdouble y, GLdouble z) {
	ULONG *qt_w = qt_reserve(9);
	qt_w[0] = (248UL << 16) | 9;
	qt_w[1] = qt_dhi(ane);
	qt_w[2] = qt_dlo(ane);
	qt_w[3] = qt_dhi(x);
	qt_w[4] = qt_dlo(x);
	qt_w[5] = qt_dhi(y);
	qt_w[6] = qt_dlo(y);
	qt_w[7] = qt_dhi(z);
	qt_w[8] = qt_dlo(z);
}
GLvoid _glRotatef(GLfloat ane, GLfloat x, GLfloat y, GLfloat z) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (249UL << 16) | 5;
	qt_w[1] = qt_f2l(ane);
	qt_w[2] = qt_f2l(x);
	qt_w[3] = qt_f2l(y);
	qt_w[4] = qt_f2l(z);
}
GLvoid _glScaled(GLdouble x, GLdouble y, GLdouble z) {
	ULONG *qt_w = qt_reserve(7);
	qt_w[0] = (250UL << 16) | 7;
	qt_w[1] = qt_dhi(x);
	qt_w[2] = qt_dlo(x);
	qt_w[3] = qt_dhi(y);
	qt_w[4] = qt_dlo(y);
	qt_w[5] = qt_dhi(z);
	qt_w[6] = qt_dlo(z);
}
GLvoid _glScalef(GLfloat x, GLfloat y, GLfloat z) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (251UL << 16) | 4;
	qt_w[1] = qt_f2l(x);
	qt_w[2] = qt_f2l(y);
	qt_w[3] = qt_f2l(z);
}
GLvoid _glScissor(GLint x, GLint y, GLsizei width, GLsizei height) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (252UL << 16) | 5;
	qt_w[1] = (ULONG) x;
	qt_w[2] = (ULONG) y;
	qt_w[3] = (ULONG) width;
	qt_w[4] = (ULONG) height;
}
GLvoid _glSelectBuffer(GLsizei size, GLuint* buffer) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (253UL << 16) | 3;
	qt_w[1] = (ULONG) size;
	qt_w[2] = QT_ADDRESS(buffer);
	qt_flush();
}
GLvoid _glShadeModel(GLenum mode) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (254UL << 16) | 2;
	qt_w[1] = (ULONG) mode;
}
GLvoid _glStencilFunc(GLenum func, GLint ref, GLuint mask) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (255UL << 16) | 4;
	qt_w[1] = (ULONG) func;
	qt_w[2] = (ULONG) ref;
	qt_w[3] = (ULONG) mask;
}
GLvoid _glStencilMask(GLuint mask) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (256UL << 16) | 2;
	qt_w[1] = (ULONG) mask;
}
GLvoid _glStencilOp(GLenum fail, GLenum zfail, GLenum zpass) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (257UL << 16) | 4;
	qt_w[1] = (ULONG) fail;
	qt_w[2] = (ULONG) zfail;
	qt_w[3] = (ULONG) zpass;
}
GLvoid _glTexCoord1d(GLdouble s) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (258UL << 16) | 3;
	qt_w[1] = qt_dhi(s);
	qt_w[2] = qt_dlo(s);
}
GLvoid _glTexCoord1dv(GLdouble* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (259UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glTexCoord1f(GLfloat s) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (260UL << 16) | 2;
	qt_w[1] = qt_f2l(s);
}
GLvoid _glTexCoord1fv(GLfloat* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (261UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glTexCoord1i(GLint s) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (262UL << 16) | 2;
	qt_w[1] = (ULONG) s;
}
GLvoid _glTexCoord1iv(GLint* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (263UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glTexCoord1s(GLshort s) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (264UL << 16) | 2;
	qt_w[1] = (ULONG) s;
}
GLvoid _glTexCoord1sv(GLshort* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (265UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glTexCoord2d(GLdouble s, GLdouble t) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (266UL << 16) | 5;
	qt_w[1] = qt_dhi(s);
	qt_w[2] = qt_dlo(s);
	qt_w[3] = qt_dhi(t);
	qt_w[4] = qt_dlo(t);
}
GLvoid _glTexCoord2dv(GLdouble* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (267UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glTexCoord2f(GLfloat s, GLfloat t) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (268UL << 16) | 3;
	qt_w[1] = qt_f2l(s);
	qt_w[2] = qt_f2l(t);
}
GLvoid _glTexCoord2fv(GLfloat* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (269UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glTexCoord2i(GLint s, GLint t) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (270UL << 16) | 3;
	qt_w[1] = (ULONG) s;
	qt_w[2] = (ULONG) t;
}
GLvoid _glTexCoord2iv(GLint* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (271UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glTexCoord2s(GLshort s, GLshort t) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (272UL << 16) | 3;
	qt_w[1] = (ULONG) s;
	qt_w[2] = (ULONG) t;
}
GLvoid _glTexCoord2sv(GLshort* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (273UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glTexCoord3d(GLdouble s, GLdouble t, GLdouble r) {
	ULONG *qt_w = qt_reserve(7);
	qt_w[0] = (274UL << 16) | 7;
	qt_w[1] = qt_dhi(s);
	qt_w[2] = qt_dlo(s);
	qt_w[3] = qt_dhi(t);
	qt_w[4] = qt_dlo(t);
	qt_w[5] = qt_dhi(r);
	qt_w[6] = qt_dlo(r);
}
GLvoid _glTexCoord3dv(GLdouble* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (275UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glTexCoord3f(GLfloat s, GLfloat t, GLfloat r) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (276UL << 16) | 4;
	qt_w[1] = qt_f2l(s);
	qt_w[2] = qt_f2l(t);
	qt_w[3] = qt_f2l(r);
}
GLvoid _glTexCoord3fv(GLfloat* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (277UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glTexCoord3i(GLint s, GLint t, GLint r) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (278UL << 16) | 4;
	qt_w[1] = (ULONG) s;
	qt_w[2] = (ULONG) t;
	qt_w[3] = (ULONG) r;
}
GLvoid _glTexCoord3iv(GLint* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (279UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glTexCoord3s(GLshort s, GLshort t, GLshort r) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (280UL << 16) | 4;
	qt_w[1] = (ULONG) s;
	qt_w[2] = (ULONG) t;
	qt_w[3] = (ULONG) r;
}
GLvoid _glTexCoord3sv(GLshort* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (281UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glTexCoord4d(GLdouble s, GLdouble t, GLdouble r, GLdouble q) {
	ULONG *qt_w = qt_reserve(9);
	qt_w[0] = (282UL << 16) | 9;
	qt_w[1] = qt_dhi(s);
	qt_w[2] = qt_dlo(s);
	qt_w[3] = qt_dhi(t);
	qt_w[4] = qt_dlo(t);
	qt_w[5] = qt_dhi(r);
	qt_w[6] = qt_dlo(r);
	qt_w[7] = qt_dhi(q);
	qt_w[8] = qt_dlo(q);
}
GLvoid _glTexCoord4dv(GLdouble* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (283UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glTexCoord4f(GLfloat s, GLfloat t, GLfloat r, GLfloat q) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (284UL << 16) | 5;
	qt_w[1] = qt_f2l(s);
	qt_w[2] = qt_f2l(t);
	qt_w[3] = qt_f2l(r);
	qt_w[4] = qt_f2l(q);
}
GLvoid _glTexCoord4fv(GLfloat* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (285UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glTexCoord4i(GLint s, GLint t, GLint r, GLint q) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (286UL << 16) | 5;
	qt_w[1] = (ULONG) s;
	qt_w[2] = (ULONG) t;
	qt_w[3] = (ULONG) r;
	qt_w[4] = (ULONG) q;
}
GLvoid _glTexCoord4iv(GLint* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (287UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glTexCoord4s(GLshort s, GLshort t, GLshort r, GLshort q) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (288UL << 16) | 5;
	qt_w[1] = (ULONG) s;
	qt_w[2] = (ULONG) t;
	qt_w[3] = (ULONG) r;
	qt_w[4] = (ULONG) q;
}
GLvoid _glTexCoord4sv(GLshort* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (289UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glTexCoordPointer(GLint size, GLenum type, GLsizei stride, GLvoid* pointer) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (290UL << 16) | 5;
	qt_w[1] = (ULONG) size;
	qt_w[2] = (ULONG) type;
	qt_w[3] = (ULONG) stride;
	qt_w[4] = QT_ADDRESS(pointer);
	qt_flush();
}
GLvoid _glTexEnvf(GLenum target, GLenum pname, GLfloat param) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (291UL << 16) | 4;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = qt_f2l(param);
}
GLvoid _glTexEnvfv(GLenum target, GLenum pname, GLfloat* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (292UL << 16) | 4;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glTexEnvi(GLenum target, GLenum pname, GLint param) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (293UL << 16) | 4;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = (ULONG) param;
}
GLvoid _glTexEnviv(GLenum target, GLenum pname, GLint* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (294UL << 16) | 4;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glTexGend(GLenum coord, GLenum pname, GLdouble param) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (295UL << 16) | 5;
	qt_w[1] = (ULONG) coord;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = qt_dhi(param);
	qt_w[4] = qt_dlo(param);
}
GLvoid _glTexGendv(GLenum coord, GLenum pname, GLdouble* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (296UL << 16) | 4;
	qt_w[1] = (ULONG) coord;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glTexGenf(GLenum coord, GLenum pname, GLfloat param) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (297UL << 16) | 4;
	qt_w[1] = (ULONG) coord;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = qt_f2l(param);
}
GLvoid _glTexGenfv(GLenum coord, GLenum pname, GLfloat* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (298UL << 16) | 4;
	qt_w[1] = (ULONG) coord;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glTexGeni(GLenum coord, GLenum pname, GLint param) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (299UL << 16) | 4;
	qt_w[1] = (ULONG) coord;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = (ULONG) param;
}
GLvoid _glTexGeniv(GLenum coord, GLenum pname, GLint* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (300UL << 16) | 4;
	qt_w[1] = (ULONG) coord;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glTexImage1D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, GLvoid* pixels) {
	ULONG *qt_w = qt_reserve(9);
	qt_w[0] = (301UL << 16) | 9;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) level;
	qt_w[3] = (ULONG) internalformat;
	qt_w[4] = (ULONG) width;
	qt_w[5] = (ULONG) border;
	qt_w[6] = (ULONG) format;
	qt_w[7] = (ULONG) type;
	qt_w[8] = QT_ADDRESS(pixels);
	qt_flush();
}
GLvoid _glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, GLvoid* pixels) {
	ULONG *qt_w = qt_reserve(10);
	qt_w[0] = (302UL << 16) | 10;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) level;
	qt_w[3] = (ULONG) internalformat;
	qt_w[4] = (ULONG) width;
	qt_w[5] = (ULONG) height;
	qt_w[6] = (ULONG) border;
	qt_w[7] = (ULONG) format;
	qt_w[8] = (ULONG) type;
	qt_w[9] = QT_ADDRESS(pixels);
	qt_flush();
}
GLvoid _glTexParameterf(GLenum target, GLenum pname, GLfloat param) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (303UL << 16) | 4;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = qt_f2l(param);
}
GLvoid _glTexParameterfv(GLenum target, GLenum pname, GLfloat* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (304UL << 16) | 4;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glTexParameteri(GLenum target, GLenum pname, GLint param) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (305UL << 16) | 4;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = (ULONG) param;
}
GLvoid _glTexParameteriv(GLenum target, GLenum pname, GLint* params) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (306UL << 16) | 4;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) pname;
	qt_w[3] = QT_ADDRESS(params);
	qt_flush();
}
GLvoid _glTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, GLvoid* pixels) {
	ULONG *qt_w = qt_reserve(8);
	qt_w[0] = (307UL << 16) | 8;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) level;
	qt_w[3] = (ULONG) xoffset;
	qt_w[4] = (ULONG) width;
	qt_w[5] = (ULONG) format;
	qt_w[6] = (ULONG) type;
	qt_w[7] = QT_ADDRESS(pixels);
	qt_flush();
}
GLvoid _glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* pixels) {
	ULONG *qt_w = qt_reserve(10);
	qt_w[0] = (308UL << 16) | 10;
	qt_w[1] = (ULONG) target;
	qt_w[2] = (ULONG) level;
	qt_w[3] = (ULONG) xoffset;
	qt_w[4] = (ULONG) yoffset;
	qt_w[5] = (ULONG) width;
	qt_w[6] = (ULONG) height;
	qt_w[7] = (ULONG) format;
	qt_w[8] = (ULONG) type;
	qt_w[9] = QT_ADDRESS(pixels);
	qt_flush();
}
GLvoid _glTranslated(GLdouble x, GLdouble y, GLdouble z) {
	ULONG *qt_w = qt_reserve(7);
	qt_w[0] = (309UL << 16) | 7;
	qt_w[1] = qt_dhi(x);
	qt_w[2] = qt_dlo(x);
	qt_w[3] = qt_dhi(y);
	qt_w[4] = qt_dlo(y);
	qt_w[5] = qt_dhi(z);
	qt_w[6] = qt_dlo(z);
}
GLvoid _glTranslatef(GLfloat x, GLfloat y, GLfloat z) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (310UL << 16) | 4;
	qt_w[1] = qt_f2l(x);
	qt_w[2] = qt_f2l(y);
	qt_w[3] = qt_f2l(z);
}
GLvoid _glVertex2d(GLdouble x, GLdouble y) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (311UL << 16) | 5;
	qt_w[1] = qt_dhi(x);
	qt_w[2] = qt_dlo(x);
	qt_w[3] = qt_dhi(y);
	qt_w[4] = qt_dlo(y);
}
GLvoid _glVertex2dv(GLdouble* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (312UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glVertex2f(GLfloat x, GLfloat y) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (313UL << 16) | 3;
	qt_w[1] = qt_f2l(x);
	qt_w[2] = qt_f2l(y);
}
GLvoid _glVertex2fv(GLfloat* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (314UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glVertex2i(GLint x, GLint y) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (315UL << 16) | 3;
	qt_w[1] = (ULONG) x;
	qt_w[2] = (ULONG) y;
}
GLvoid _glVertex2iv(GLint* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (316UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glVertex2s(GLshort x, GLshort y) {
	ULONG *qt_w = qt_reserve(3);
	qt_w[0] = (317UL << 16) | 3;
	qt_w[1] = (ULONG) x;
	qt_w[2] = (ULONG) y;
}
GLvoid _glVertex2sv(GLshort* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (318UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glVertex3d(GLdouble x, GLdouble y, GLdouble z) {
	ULONG *qt_w = qt_reserve(7);
	qt_w[0] = (319UL << 16) | 7;
	qt_w[1] = qt_dhi(x);
	qt_w[2] = qt_dlo(x);
	qt_w[3] = qt_dhi(y);
	qt_w[4] = qt_dlo(y);
	qt_w[5] = qt_dhi(z);
	qt_w[6] = qt_dlo(z);
}
GLvoid _glVertex3dv(GLdouble* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (320UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glVertex3f(GLfloat x, GLfloat y, GLfloat z) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (321UL << 16) | 4;
	qt_w[1] = qt_f2l(x);
	qt_w[2] = qt_f2l(y);
	qt_w[3] = qt_f2l(z);
}
GLvoid _glVertex3fv(GLfloat* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (322UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glVertex3i(GLint x, GLint y, GLint z) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (323UL << 16) | 4;
	qt_w[1] = (ULONG) x;
	qt_w[2] = (ULONG) y;
	qt_w[3] = (ULONG) z;
}
GLvoid _glVertex3iv(GLint* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (324UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glVertex3s(GLshort x, GLshort y, GLshort z) {
	ULONG *qt_w = qt_reserve(4);
	qt_w[0] = (325UL << 16) | 4;
	qt_w[1] = (ULONG) x;
	qt_w[2] = (ULONG) y;
	qt_w[3] = (ULONG) z;
}
GLvoid _glVertex3sv(GLshort* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (326UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glVertex4d(GLdouble x, GLdouble y, GLdouble z, GLdouble w) {
	ULONG *qt_w = qt_reserve(9);
	qt_w[0] = (327UL << 16) | 9;
	qt_w[1] = qt_dhi(x);
	qt_w[2] = qt_dlo(x);
	qt_w[3] = qt_dhi(y);
	qt_w[4] = qt_dlo(y);
	qt_w[5] = qt_dhi(z);
	qt_w[6] = qt_dlo(z);
	qt_w[7] = qt_dhi(w);
	qt_w[8] = qt_dlo(w);
}
GLvoid _glVertex4dv(GLdouble* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (328UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glVertex4f(GLfloat x, GLfloat y, GLfloat z, GLfloat w) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (329UL << 16) | 5;
	qt_w[1] = qt_f2l(x);
	qt_w[2] = qt_f2l(y);
	qt_w[3] = qt_f2l(z);
	qt_w[4] = qt_f2l(w);
}
GLvoid _glVertex4fv(GLfloat* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (330UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glVertex4i(GLint x, GLint y, GLint z, GLint w) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (331UL << 16) | 5;
	qt_w[1] = (ULONG) x;
	qt_w[2] = (ULONG) y;
	qt_w[3] = (ULONG) z;
	qt_w[4] = (ULONG) w;
}
GLvoid _glVertex4iv(GLint* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (332UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glVertex4s(GLshort x, GLshort y, GLshort z, GLshort w) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (333UL << 16) | 5;
	qt_w[1] = (ULONG) x;
	qt_w[2] = (ULONG) y;
	qt_w[3] = (ULONG) z;
	qt_w[4] = (ULONG) w;
}
GLvoid _glVertex4sv(GLshort* v) {
	ULONG *qt_w = qt_reserve(2);
	qt_w[0] = (334UL << 16) | 2;
	qt_w[1] = QT_ADDRESS(v);
	qt_flush();
}
GLvoid _glVertexPointer(GLint size, GLenum type, GLsizei stride, GLvoid* pointer) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (335UL << 16) | 5;
	qt_w[1] = (ULONG) size;
	qt_w[2] = (ULONG) type;
	qt_w[3] = (ULONG) stride;
	qt_w[4] = QT_ADDRESS(pointer);
	qt_flush();
}
GLvoid _glViewport(GLint x, GLint y, GLsizei width, GLsizei height) {
	ULONG *qt_w = qt_reserve(5);
	qt_w[0] = (336UL << 16) | 5;
	qt_w[1] = (ULONG) x;
	qt_w[2] = (ULONG) y;
	qt_w[3] = (ULONG) width;
	qt_w[4] = (ULONG) height;
}
